# Numpy 

In [1]:
# what is numpy
# Numpy is genral purpose array processing package, it provides high performance multi dimensional array object and tools for working with these array


In [4]:
import numpy as np

In [5]:
np.array([1,2,3,4,5,6,7,8])                   # create array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
x=np.array([1,2,3,4,5,6,7,8])

In [7]:
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
type(x)                                #  for check the type 'x'

numpy.ndarray

In [10]:
x.ndim                                 # check the dimension

1

In [11]:
x.size                                 # showes the how many element present in given array

8

In [12]:
x.shape                                 # these one dimension so we get o/p (8,) means 8*1 

(8,)

In [13]:
x.dtype                                 # show data type of element present in given array

dtype('int32')

In [20]:
x=np.array([1,2.3,2,3,5,55,54,58])          # create float element in array

In [15]:
x.dtype                                   # we get dtype  float64 

dtype('float64')

In [16]:
x=np.array(['a','bhcb'])                 # we can also pass hetrogeneous data

In [17]:
x.dtype                                   

dtype('<U4')

In [21]:
a=x.reshape(2,4)                         # to modify aaray into given shape (dimensione)

In [22]:
a

array([[ 1. ,  2.3,  2. ,  3. ],
       [ 5. , 55. , 54. , 58. ]])

In [23]:
a.ndim                                      # to chcek the dimensione of given array

2

In [25]:
x                                           # slicing 

array([ 1. ,  2.3,  2. ,  3. ,  5. , 55. , 54. , 58. ])

In [26]:
x[1:5]

array([2.3, 2. , 3. , 5. ])

In [27]:
x[::-1]                                      # we use '-' index also  for reversing the order

array([58. , 54. , 55. ,  5. ,  3. ,  2. ,  2.3,  1. ])

In [28]:
x[-1:]

array([58.])

In [31]:
x[1:6:2]

array([ 2.3,  3. , 55. ])

In [32]:
a


array([[ 1. ,  2.3,  2. ,  3. ],
       [ 5. , 55. , 54. , 58. ]])

In [33]:
a[0]

array([1. , 2.3, 2. , 3. ])

In [34]:
a[0:1]

array([[1. , 2.3, 2. , 3. ]])

In [35]:
a[0:2]

array([[ 1. ,  2.3,  2. ,  3. ],
       [ 5. , 55. , 54. , 58. ]])

In [36]:
d=np.array([[4,5,6],[7,8,9]])

In [38]:
d[1:]

array([[7, 8, 9]])

In [39]:
d.ndim

2

In [41]:
d[0][1]

5

In [42]:
d[1][2]

9

In [2]:
import numpy as np

In [13]:
e=np.array([1,2,3,45,6,5,4,78,8,9,11,23])

In [14]:
e.reshape(3,4)

array([[ 1,  2,  3, 45],
       [ 6,  5,  4, 78],
       [ 8,  9, 11, 23]])

In [15]:
e[0:2]

array([1, 2])

In [17]:
e[::]

array([ 1,  2,  3, 45,  6,  5,  4, 78,  8,  9, 11, 23])

In [19]:
e[0:2]

array([1, 2])

In [20]:
e[0]=45                            # we can  change the element in array

In [21]:
e

array([45,  2,  3, 45,  6,  5,  4, 78,  8,  9, 11, 23])

In [22]:
e

array([45,  2,  3, 45,  6,  5,  4, 78,  8,  9, 11, 23])

In [25]:
m=e.reshape(3,4)

In [26]:
m


array([[45,  2,  3, 45],
       [ 6,  5,  4, 78],
       [ 8,  9, 11, 23]])

In [27]:
m[0:3]

array([[45,  2,  3, 45],
       [ 6,  5,  4, 78],
       [ 8,  9, 11, 23]])

In [28]:
m[0][2]

3

In [29]:
m[0][1]=45

In [30]:
m

array([[45, 45,  3, 45],
       [ 6,  5,  4, 78],
       [ 8,  9, 11, 23]])

In [31]:
m[::2]

array([[45, 45,  3, 45],
       [ 8,  9, 11, 23]])

In [32]:
m[::,2]

array([ 3,  4, 11])

In [37]:
a=m[::,2]
b=m[::,0]
a,b=b,a

In [38]:
m

array([[45, 45, 45, 45],
       [ 6,  5,  6, 78],
       [ 8,  9,  8, 23]])

In [39]:
m[0::]

array([[45, 45, 45, 45],
       [ 6,  5,  6, 78],
       [ 8,  9,  8, 23]])

In [40]:
m[::-1]

array([[ 8,  9,  8, 23],
       [ 6,  5,  6, 78],
       [45, 45, 45, 45]])

In [41]:
m[::-2]

array([[ 8,  9,  8, 23],
       [45, 45, 45, 45]])

In [42]:
m[0:1]

array([[45, 45, 45, 45]])

In [43]:
m[1,2]

6

In [44]:
m[2,3]

23

In [67]:
m


array([[45, 45, 45, 45],
       [78,  5,  6, 78],
       [45, 45, 45, 45]])

In [46]:
m[::,2]

array([45,  6,  8])

In [47]:
m[::,0]

array([45,  6,  8])

In [48]:
m[::,3]

array([45, 78, 23])

In [50]:
a=m[::,3]
m[::,0]=a

In [51]:
m

array([[45, 45, 45, 45],
       [78,  5,  6, 78],
       [23,  9,  8, 23]])

In [55]:
m[2:3]

array([[45, 45, 45, 45]])

In [110]:
m[0:2]


array([[45, 45, 45, 45],
       [78,  5,  6, 78]])

In [57]:
m[0,2]

45

In [69]:
m[::,3]

array([45, 78, 45])

## ARRAY AND FUNCTIONS

In [81]:
import numpy as np

In [82]:
x=np.array(([1,2,3,4,5,6,7,8,9,10,11,21]),dtype=np.float64)

In [84]:
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 21.])

In [85]:
l=[4,8,3,5,2]
d=np.array(l)

In [86]:
d

array([4, 8, 3, 5, 2])

In [88]:
x=d.reshape(1,5)

In [92]:
x

array([[4, 8, 3, 5, 2]])

In [93]:
x=np.arange(10)                    # arange work as python range   

In [94]:
x                                   # we get 0-9 element

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
x=np.arange(0,20,2)                  # syntex is [start,stop,step]

In [99]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [101]:
x.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [102]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11,21])

In [107]:
x=x.reshape(3,4)

In [108]:
x[::2,::3]=500                              # value assign to given element

In [111]:
x

array([[500,   2,   3, 500],
       [  5,   6,   7,   8],
       [500,  10,  11, 500]])

In [115]:
x[1:3:2,1:3]=50

In [116]:
x

array([[500,   2,   3, 500],
       [  5,  50,  50,   8],
       [500,  10,  11, 500]])

In [118]:
x[1,1:3]=650

In [119]:
x

array([[500,   2,   3, 500],
       [  5, 650, 650,   8],
       [500,  10,  11, 500]])

In [120]:
x[::,::-1]

array([[500,   3,   2, 500],
       [  8, 650, 650,   5],
       [500,  11,  10, 500]])

In [121]:
x[::-1,::]

array([[500,  10,  11, 500],
       [  5, 650, 650,   8],
       [500,   2,   3, 500]])

In [122]:
x[::-1,::-1]

array([[500,  11,  10, 500],
       [  8, 650, 650,   5],
       [500,   3,   2, 500]])

In [123]:
z=np.array({4,58,10,4,12,5,3,4,10})

In [124]:
z

array({3, 4, 5, 10, 12, 58}, dtype=object)

In [125]:
np.zeros((5,5))                         # to cerate all zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [126]:
np.ones((4,5))                        # to cerate all ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [128]:
x

array([[500,   2,   3, 500],
       [  5, 650, 650,   8],
       [500,  10,  11, 500]])

In [130]:
x.shape

(3, 4)

In [132]:
u=x.flatten()                      # convert in to one dimensione

In [133]:
u

array([500,   2,   3, 500,   5, 650, 650,   8, 500,  10,  11, 500])

In [134]:
d=x.ravel()                        # it converts one d

In [135]:
d

array([500,   2,   3, 500,   5, 650, 650,   8, 500,  10,  11, 500])

In [ ]:
# flatten is a method of an ndarray(numpy)
# ravel is libary level function hence u can pass any object

In [136]:
d.cumsum()                           # for cumulative sum of array       

array([ 500,  502,  505, 1005, 1010, 1660, 2310, 2318, 2818, 2828, 2839,
       3339], dtype=int32)

In [137]:
x.cumsum()

array([ 500,  502,  505, 1005, 1010, 1660, 2310, 2318, 2818, 2828, 2839,
       3339], dtype=int32)

In [146]:
x.size                                # no of element present in 

12

In [147]:
x.itemsize

4

In [148]:
x.data                              # address

In [154]:
c=np.array(([10,3],[5,14]),dtype=np.complex)  # u can change dtype also
c

array([[10.+0.j,  3.+0.j],
       [ 5.+0.j, 14.+0.j]])

In [157]:
np.zeros((3,4),dtype=np.int8)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [158]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [159]:
# what is def between empty and ones

In [162]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [166]:
x=np.arange(2,10).reshape(2,4)
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [168]:
x=np.arange(2,10).reshape(2,4)
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [169]:
v=[1,2,3,4]
w=np.tile(v,(4,2))
w                                      # tile is use for create replicaa

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4]])

In [170]:
v=[1,2,3,4]
w=np.tile(v,(4,1))
w 

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [171]:
v=[1,2,3,4]
w=np.tile(np.arange(1,3),(4,1))
w 

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

In [173]:
np.linspace(2,21,50)                # (start stop values)

array([ 2.        ,  2.3877551 ,  2.7755102 ,  3.16326531,  3.55102041,
        3.93877551,  4.32653061,  4.71428571,  5.10204082,  5.48979592,
        5.87755102,  6.26530612,  6.65306122,  7.04081633,  7.42857143,
        7.81632653,  8.20408163,  8.59183673,  8.97959184,  9.36734694,
        9.75510204, 10.14285714, 10.53061224, 10.91836735, 11.30612245,
       11.69387755, 12.08163265, 12.46938776, 12.85714286, 13.24489796,
       13.63265306, 14.02040816, 14.40816327, 14.79591837, 15.18367347,
       15.57142857, 15.95918367, 16.34693878, 16.73469388, 17.12244898,
       17.51020408, 17.89795918, 18.28571429, 18.67346939, 19.06122449,
       19.44897959, 19.83673469, 20.2244898 , 20.6122449 , 21.        ])

In [1]:
from numpy import pi               # math (pi)

In [175]:
x=np.linspace(0,2*pi,50)
y=np.sin(x)

In [176]:
y

array([ 0.00000000e+00,  1.27877162e-01,  2.53654584e-01,  3.75267005e-01,
        4.90717552e-01,  5.98110530e-01,  6.95682551e-01,  7.81831482e-01,
        8.55142763e-01,  9.14412623e-01,  9.58667853e-01,  9.87181783e-01,
        9.99486216e-01,  9.95379113e-01,  9.74927912e-01,  9.38468422e-01,
        8.86599306e-01,  8.20172255e-01,  7.40277997e-01,  6.48228395e-01,
        5.45534901e-01,  4.33883739e-01,  3.15108218e-01,  1.91158629e-01,
        6.40702200e-02, -6.40702200e-02, -1.91158629e-01, -3.15108218e-01,
       -4.33883739e-01, -5.45534901e-01, -6.48228395e-01, -7.40277997e-01,
       -8.20172255e-01, -8.86599306e-01, -9.38468422e-01, -9.74927912e-01,
       -9.95379113e-01, -9.99486216e-01, -9.87181783e-01, -9.58667853e-01,
       -9.14412623e-01, -8.55142763e-01, -7.81831482e-01, -6.95682551e-01,
       -5.98110530e-01, -4.90717552e-01, -3.75267005e-01, -2.53654584e-01,
       -1.27877162e-01, -2.44929360e-16])

In [2]:
import numpy as np

In [5]:
x=np.arange(1,13).reshape(3,4)

In [18]:
x

array([[-1,  2, -1, 40],
       [-1,  6, -1,  8],
       [-1, 10, -1, 40]])

In [19]:
x[::,::2]=45

In [20]:
x

array([[45,  2, 45, 40],
       [45,  6, 45,  8],
       [45, 10, 45, 40]])

In [21]:
x[::,2]=47,48,49

In [22]:
x

array([[45,  2, 47, 40],
       [45,  6, 48,  8],
       [45, 10, 49, 40]])

In [58]:
x[1::,1:3:]+78


array([[205]])

In [59]:
x

array([[ 84, 126],
       [ 88, 127]])

In [60]:
x=np.array([[45,  2, 45, 40],
       [45,  6, 45,  8],
       [45, 10, 45, 40]])

In [61]:
x

array([[45,  2, 45, 40],
       [45,  6, 45,  8],
       [45, 10, 45, 40]])

In [65]:
x=np.linspace(1,5,25)
y=np.sin(x)
y

array([ 0.84147098,  0.91944498,  0.9719379 ,  0.99749499,  0.99540796,
        0.96573465,  0.90929743,  0.82766035,  0.72308588,  0.59847214,
        0.45727263,  0.30340047,  0.14112001, -0.02507139, -0.19056796,
       -0.35078323, -0.50127705, -0.63787871, -0.7568025 , -0.85475261,
       -0.9290145 , -0.97753012, -0.99895492, -0.99269514, -0.95892427])

In [67]:
v=[12,66,265]
x=np.tile(v,(4,3))
x

array([[ 12,  66, 265,  12,  66, 265,  12,  66, 265],
       [ 12,  66, 265,  12,  66, 265,  12,  66, 265],
       [ 12,  66, 265,  12,  66, 265,  12,  66, 265],
       [ 12,  66, 265,  12,  66, 265,  12,  66, 265]])

In [70]:
x.size

36

In [71]:
x.shape

(4, 9)

In [72]:
np.linspace(0,4,20)

array([0.        , 0.21052632, 0.42105263, 0.63157895, 0.84210526,
       1.05263158, 1.26315789, 1.47368421, 1.68421053, 1.89473684,
       2.10526316, 2.31578947, 2.52631579, 2.73684211, 2.94736842,
       3.15789474, 3.36842105, 3.57894737, 3.78947368, 4.        ])

In [73]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [74]:
x

array([[ 12,  66, 265,  12,  66, 265,  12,  66, 265],
       [ 12,  66, 265,  12,  66, 265,  12,  66, 265],
       [ 12,  66, 265,  12,  66, 265,  12,  66, 265],
       [ 12,  66, 265,  12,  66, 265,  12,  66, 265]])

In [75]:
y=x[1:3:-1]

In [77]:
x

array([[ 12,  66, 265,  12,  66, 265,  12,  66, 265],
       [ 12,  66, 265,  12,  66, 265,  12,  66, 265],
       [ 12,  66, 265,  12,  66, 265,  12,  66, 265],
       [ 12,  66, 265,  12,  66, 265,  12,  66, 265]])

In [78]:
x[1:3:-1]

array([], shape=(0, 9), dtype=int32)

In [81]:
x[1:3:]=20

In [82]:
x

array([[ 12,  66, 265,  12,  66, 265,  12,  66, 265],
       [ 20,  20,  20,  20,  20,  20,  20,  20,  20],
       [ 20,  20,  20,  20,  20,  20,  20,  20,  20],
       [ 12,  66, 265,  12,  66, 265,  12,  66, 265]])

# basice operation


In [7]:
import numpy as np
a=np.array([[20,30,40,50]])
b=np.arange(4)
c=a+b
d=a*b

f=a//b
c,d,f

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in floor_divide
  import sys


(array([[20, 31, 42, 53]]),
 array([[  0,  30,  80, 150]]),
 array([[ 0, 30, 20, 16]], dtype=int32))

In [8]:
# u can do it in 3d,

In [9]:
b

array([0, 1, 2, 3])

In [10]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [12]:
np.sin(a)*100

array([[ 91.29452507, -98.80316241,  74.51131605, -26.23748537]])

In [13]:
a=np.arange(15,40)
a

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39])

In [17]:
a<=35

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False])

In [20]:
a.all()# chcek zero
a.any()# zero allowed

True

In [23]:
a==20

array([False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [24]:
A=np.array([[1,1],
            [0,1]])
B=np.array([[2,0],
            [3,4]])


In [25]:
A * B  # elementwise

array([[2, 0],
       [0, 4]])

In [26]:
A @ B    # matrix product

array([[5, 4],
       [3, 4]])

In [28]:
A .dot(B)   # same as @

array([[5, 4],
       [3, 4]])

In [29]:
np.random.random(10)                # for random value

array([0.70615762, 0.23698233, 0.8395736 , 0.71738421, 0.91527049,
       0.01492744, 0.60110567, 0.54504408, 0.48149209, 0.10038342])

In [35]:
np.random.random((4,4,5))

array([[[0.62338201, 0.67764859, 0.3783502 , 0.55482106, 0.79695005],
        [0.15116475, 0.50772691, 0.03004539, 0.81823769, 0.6755172 ],
        [0.87898686, 0.24898395, 0.1783698 , 0.73141345, 0.02549897],
        [0.73316797, 0.94659598, 0.55920609, 0.24817749, 0.35560895]],

       [[0.38665078, 0.07123689, 0.86991179, 0.4900403 , 0.7231419 ],
        [0.07425731, 0.839511  , 0.21026734, 0.19133853, 0.89951709],
        [0.6314746 , 0.42157208, 0.82762602, 0.96865934, 0.55331776],
        [0.40026067, 0.87909066, 0.7296719 , 0.79589224, 0.3488886 ]],

       [[0.57232903, 0.87303686, 0.0783758 , 0.14237097, 0.04260461],
        [0.09981426, 0.26341353, 0.76348412, 0.24741103, 0.60104912],
        [0.23333505, 0.59571424, 0.94415172, 0.11114431, 0.36188592],
        [0.74771703, 0.86848012, 0.65663562, 0.30600105, 0.53663051]],

       [[0.72302298, 0.00999851, 0.88599391, 0.1436494 , 0.10150211],
        [0.64333917, 0.58720157, 0.10447964, 0.6654288 , 0.26792786],
        [0.153

In [30]:
np.random.rand(10)             # its gives some time negativevalue

array([0.48026406, 0.61555661, 0.89616913, 0.59269593, 0.89748095,
       0.12849066, 0.31115824, 0.54732788, 0.36386695, 0.22283701])

In [33]:
np.random.rand(4,4,5)

array([[[0.81330118, 0.98292222, 0.1054523 , 0.89524437, 0.26922582],
        [0.71224593, 0.10947158, 0.76071442, 0.00623033, 0.44893331],
        [0.23680386, 0.07831975, 0.16799748, 0.14871974, 0.44099436],
        [0.97319634, 0.60349252, 0.06445521, 0.77928127, 0.00166464]],

       [[0.05372913, 0.00794603, 0.49995969, 0.83564579, 0.30243792],
        [0.0578828 , 0.15957856, 0.02193673, 0.9008784 , 0.6492215 ],
        [0.90662113, 0.56912926, 0.09799245, 0.11843534, 0.99460954],
        [0.79345083, 0.56911311, 0.80647284, 0.74251999, 0.55150195]],

       [[0.65525382, 0.32808365, 0.74860788, 0.57888933, 0.35184116],
        [0.90591894, 0.82014775, 0.51683312, 0.7851307 , 0.94483199],
        [0.89997407, 0.39952783, 0.75991431, 0.50356398, 0.37187045],
        [0.78367188, 0.14942905, 0.3890519 , 0.10846223, 0.76567638]],

       [[0.57422438, 0.92063194, 0.54063899, 0.16432708, 0.53423513],
        [0.53182522, 0.64685773, 0.46874004, 0.05533388, 0.09810486],
        [0.579

In [31]:
np.random.randint(2,20,10)            # its give int value

array([ 2, 16,  3, 13, 17, 17,  3, 10, 14,  8])

In [36]:
# float = 8 bit int=4 bit   hence float main int add ho sakata hai but int float add nahi ho sakat haiiiiii

In [38]:
a=np.ones((2,3),dtype=int)
b= np.random.random((2,3))
a*=3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [39]:
b += a

In [40]:
b

array([[3.98183988, 3.07026121, 3.00662014],
       [3.90639843, 3.92152267, 3.07790511]])

In [43]:
a=np.arange(2,12).reshape(5,2)

In [44]:
a.sum()

65

In [45]:
a.max()

11

In [46]:
a.min()

2

In [47]:
a.mean()

6.5

In [49]:
a.std()

2.8722813232690143

In [50]:
a.argmax()        # gives index of max no

9

In [51]:
a.argmin()# gives index of min no

0

In [52]:
len(a)

5

In [53]:
a.sum(axis=0)# 0= for coloum and 1= for row

array([30, 35])

In [54]:
a

array([[ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [55]:
a.sum(axis=1)

array([ 5,  9, 13, 17, 21])

In [56]:
a.argmin(axis=1)

array([0, 0, 0, 0, 0], dtype=int64)

In [57]:
a.cumsum(axis=1)

array([[ 2,  5],
       [ 4,  9],
       [ 6, 13],
       [ 8, 17],
       [10, 21]], dtype=int32)

In [58]:
a.min(axis=1)

array([ 2,  4,  6,  8, 10])

In [59]:
a.max(axis=0)

array([10, 11])

# NORMAL BASIC MATHS

In [60]:
x=np.arange(1,5).reshape(2,2)
y=np.arange(6,10).reshape(2,2)


In [61]:
np.add(x,y)

array([[ 7,  9],
       [11, 13]])

In [63]:
np.subtract(x,y)

array([[-5, -5],
       [-5, -5]])

In [64]:
np.divide(x,y)

array([[0.16666667, 0.28571429],
       [0.375     , 0.44444444]])

In [65]:
np.multiply(x,y)

array([[ 6, 14],
       [24, 36]])

In [68]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [70]:
np.log(x)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

# UNIVERSAL FUNCTION

In [71]:
B = np.arange(5)
B
np.exp(B)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [72]:
z=np.array([778,54,5,5656,565,2,2,6,26,5])
z.sort()

In [73]:
z

array([   2,    2,    5,    5,    6,   26,   54,  565,  778, 5656])

In [74]:
z.argsort() # gives the index of  sort o/p

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [77]:
x=np.array([1,2,3,4,5,0,2,0,3,6])

In [78]:
x.nonzero() # skip the index of zero

(array([0, 1, 2, 3, 4, 6, 8, 9], dtype=int64),)

# MULTI DIMENSION ARRAY

In [3]:
import numpy as np
n=np.arange(4,24).reshape(4,5)
n

array([[ 4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23]])

In [80]:
# itration 
for row in n:
    for cell in row:
        print(cell)

4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [4]:
# print indexing  of elemnet 

In [5]:
n

array([[ 4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23]])

In [6]:
n[1:3,1:3]

array([[10, 11],
       [15, 16]])

In [7]:
n[:,1:3]

array([[ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [8]:
n[1:3,:]

array([[ 9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18]])

In [9]:
n[::3,::4]=100

In [10]:
n

array([[100,   5,   6,   7, 100],
       [  9,  10,  11,  12,  13],
       [ 14,  15,  16,  17,  18],
       [100,  20,  21,  22, 100]])

In [11]:
n[::2,::4]=125

In [12]:
n

array([[125,   5,   6,   7, 125],
       [  9,  10,  11,  12,  13],
       [125,  15,  16,  17, 125],
       [100,  20,  21,  22, 100]])

In [13]:
n

array([[125,   5,   6,   7, 125],
       [  9,  10,  11,  12,  13],
       [125,  15,  16,  17, 125],
       [100,  20,  21,  22, 100]])

In [14]:
b=n

In [15]:
b

array([[125,   5,   6,   7, 125],
       [  9,  10,  11,  12,  13],
       [125,  15,  16,  17, 125],
       [100,  20,  21,  22, 100]])

# shape manipulation

In [20]:
n.reshape((5,4),order ='F')             # its filled flottern style (zig-zag)

array([[125,  10,  16,  22],
       [  9,  15,  21, 125],
       [125,  20,   7,  13],
       [100,   6,  12, 125],
       [  5,  11,  17, 100]])

In [21]:
np.invert(n)

array([[-126,   -6,   -7,   -8, -126],
       [ -10,  -11,  -12,  -13,  -14],
       [-126,  -16,  -17,  -18, -126],
       [-101,  -21,  -22,  -23, -101]], dtype=int32)

In [22]:
n.T # transpose

array([[125,   9, 125, 100],
       [  5,  10,  15,  20],
       [  6,  11,  16,  21],
       [  7,  12,  17,  22],
       [125,  13, 125, 100]])

In [23]:
n.resize(10,2)              

In [24]:
n

array([[125,   5],
       [  6,   7],
       [125,   9],
       [ 10,  11],
       [ 12,  13],
       [125,  15],
       [ 16,  17],
       [125, 100],
       [ 20,  21],
       [ 22, 100]])

# stacking together different arrays

In [25]:
 # horizonatl - row

In [30]:
a=np.array([[1,2,3,4]]).reshape(2,2)
b=np.array([5,6,7,8]).reshape(2,2)

In [31]:
a

array([[1, 2],
       [3, 4]])

In [32]:
b

array([[5, 6],
       [7, 8]])

In [33]:
np.hstack((b,a))

array([[5, 6, 1, 2],
       [7, 8, 3, 4]])

In [5]:
import numpy as np

In [6]:
a=np.array([[1,2,3,4]]).reshape(2,2)
b=np.array([5,6,7,8]).reshape(2,2)

In [7]:
a

array([[1, 2],
       [3, 4]])

In [8]:
b

array([[5, 6],
       [7, 8]])

In [9]:
np.column_stack((a,b))     # work as hstack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [10]:
np.row_stack((a,b))          # work as vstack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
# it's work diffrent in 1 d

In [12]:
n=np.array([10,20,30,40,50,60]).reshape(1,-1)  # -1 work as last element and it's remaing also u use (2,-1) same as (2,3)

In [13]:
n

array([[10, 20, 30, 40, 50, 60]])

In [14]:
n=np.array([10,20,30,40,50,60]).reshape(1,-1)

In [15]:
n

array([[10, 20, 30, 40, 50, 60]])

In [16]:
# 1 d to 2 d

In [17]:
from  numpy import newaxis        # work same as (6,1)        
n[:,newaxis]

array([[[10, 20, 30, 40, 50, 60]]])

In [18]:
np.r_[1:5,10,20]

array([ 1,  2,  3,  4, 10, 20])

In [19]:
(np.r_[1:9:2,10,20])

array([ 1,  3,  5,  7, 10, 20])

In [21]:
np.c_[[1,2,3],[3,6,7]]

array([[1, 3],
       [2, 6],
       [3, 7]])

In [22]:
a=np.array(range(1,25)).reshape(2,12)

In [23]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [28]:
np.hsplit(a,3)            # partion  equl  3 part  np.vsplit (a,3)[0]

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [29]:
a=np.array(range(1,25)).reshape(12,2)

In [30]:
np.vsplit(a,3)

[array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]), array([[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]), array([[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]])]

#  copies and views

In [31]:
# what is shallow and deep

In [32]:
a=np.array(range(1,25)).reshape(12,2)

In [33]:
c=a.copy()

In [34]:
c

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [35]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [36]:
c is a

False

In [37]:
id(c), id(a)

(2245527457264, 2245527454064)

In [39]:
c[0,1]=2000

In [42]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [43]:
del c

In [45]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [46]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [47]:
c=a.copy()

In [55]:
a.flags


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [54]:
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [50]:
a.flags.owndata

False

In [51]:
c.flags.owndata

True

In [58]:
d = c.view()
d

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [59]:
d is c

False

In [60]:
d.base is c

True

In [62]:
d[0,1]=100

In [63]:
d

array([[  1, 100],
       [  3,   4],
       [  5,   6],
       [  7,   8],
       [  9,  10],
       [ 11,  12],
       [ 13,  14],
       [ 15,  16],
       [ 17,  18],
       [ 19,  20],
       [ 21,  22],
       [ 23,  24]])

In [64]:
c

array([[  1, 100],
       [  3,   4],
       [  5,   6],
       [  7,   8],
       [  9,  10],
       [ 11,  12],
       [ 13,  14],
       [ 15,  16],
       [ 17,  18],
       [ 19,  20],
       [ 21,  22],
       [ 23,  24]])

# indexing with array of indices

In [65]:
a=np.arange(1,13)**2

In [66]:
a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [68]:
i=np.array([4,8,6,7,2,1,3,10])
a[i]

array([ 25,  81,  49,  64,   9,   4,  16, 121], dtype=int32)

In [69]:
j= np.array([[3,4],[10,11]])
a[j]

array([[ 16,  25],
       [121, 144]], dtype=int32)

In [70]:
i

array([ 4,  8,  6,  7,  2,  1,  3, 10])

In [71]:
i[[1,5,3]]=985
i

array([  4, 985,   6, 985,   2, 985,   3,  10])

In [72]:
i[[1,5,3]]=[985,89,56]
i

array([  4, 985,   6,  56,   2,  89,   3,  10])

In [73]:
# python's += consrtuct

In [74]:
a[:]+=2

In [75]:
a

array([  3,   6,  11,  18,  27,  38,  51,  66,  83, 102, 123, 146],
      dtype=int32)

In [76]:
i[[1,5,3]]+=[985,89,56]
i

array([   4, 1970,    6,  112,    2,  178,    3,   10])

# indexing with boolen arrays


In [77]:
a

array([  3,   6,  11,  18,  27,  38,  51,  66,  83, 102, 123, 146],
      dtype=int32)

In [78]:
a >4

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [79]:
a=a.reshape(4,3)

In [80]:
a

array([[  3,   6,  11],
       [ 18,  27,  38],
       [ 51,  66,  83],
       [102, 123, 146]], dtype=int32)

In [82]:
b= a <50
b

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [83]:
a[b]  # default is true value and 1 dimensione 

array([ 3,  6, 11, 18, 27, 38], dtype=int32)

In [84]:
a[b==False]

array([ 51,  66,  83, 102, 123, 146], dtype=int32)

In [86]:
a[a>4]

array([  6,  11,  18,  27,  38,  51,  66,  83, 102, 123, 146], dtype=int32)

In [88]:
b

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [90]:
a=a.reshape(3,4)

In [91]:
a

array([[  3,   6,  11,  18],
       [ 27,  38,  51,  66],
       [ 83, 102, 123, 146]], dtype=int32)

In [92]:
b1 =np.array([False,True,True])   #  fo row liya humne

In [93]:
b2= np.array([True, False, True,False])

In [96]:
a[b1]

array([[ 27,  38,  51,  66],
       [ 83, 102, 123, 146]], dtype=int32)

In [97]:
a[:,b2]

array([[  3,  11],
       [ 27,  51],
       [ 83, 123]], dtype=int32)

In [98]:
a[b1,b2]

array([ 27, 123], dtype=int32)

In [99]:
a

array([[  3,   6,  11,  18],
       [ 27,  38,  51,  66],
       [ 83, 102, 123, 146]], dtype=int32)

In [1]:
import numpy as np

In [4]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [5]:
a.transpose()   # same as T 

array([[1, 3],
       [2, 4]])

In [7]:
u= np.eye(3)    # unit 2 x 2 matrix ; "eye" represents "I"
u

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.trace (u)   # trace returns the sum  of digonals

3.0

#   strurcture array

In [15]:
x= np.array([('sham',90,54.2),('tarun',30,85.5)])
x.dtype

dtype('<U5')

In [16]:
x= np.array([('sham',90,54.2),('tarun',30,85.5)],dtype=[('n','U10'),('a','int32'),('w','float64')])
x.dtype          # by the help of we can change data type

dtype([('n', '<U10'), ('a', '<i4'), ('w', '<f8')])

In [17]:
x[0]

('sham', 90, 54.2)

In [18]:
x[1]

('tarun', 30, 85.5)

In [20]:
x['n'][0]

'sham'

In [21]:
x['w']

array([54.2, 85.5])

In [23]:
x['n'][1][2]

'r'

In [24]:
x['a'][0]=45

In [25]:
x

array([('sham', 45, 54.2), ('tarun', 30, 85.5)],
      dtype=[('n', '<U10'), ('a', '<i4'), ('w', '<f8')])